# Generated by Django 4.2.16 on 2024-09-10 20:20
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models

def set_auth_groups_for_roles(apps, schema_editor):
    AGOLRole = apps.get_model('accounts', 'AGOLRole')
    AGOLGroup = apps.get_model('accounts', 'AGOLGroup')
    try:
        r = AGOLRole.objects.get(pk=11)
        if r.auth_groups.count() == 0:
            groups = AGOLGroup.objects.filter(agol_id=1, is_auth_group=True).exclude(id='75a06d76-49b2-426f-b2a8-92f26fc5d1d1')
            r.auth_groups.set(groups)
    except ObjectDoesNotExist:
        pass

    try:
        r = AGOLRole.objects.get(pk=12)
        if r.auth_groups.count() == 0:
            groups = AGOLGroup.objects.filter(id='75a06d76-49b2-426f-b2a8-92f26fc5d1d1')
            r.auth_groups.set(groups)
    except ObjectDoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0031_protecteddataset_alter_accountrequests_username_and_more'),
    ]

    operations = [
        migrations.RunPython(set_auth_groups_for_roles, migrations.RunPython.noop)
    ]
